spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/biblioteca
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: "author_service"
server:
  port: 8081
book:
  service:
    url: http://localhost:8081/api/v1/books